### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by maelle** [pachamaltese/cartografias-censo2017#1]
@pachadotdev could we transfer this repository back to your account, as it's not a package?

@ropensci/admin @jeroen

**Comment by pachadotdev** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Maëlle Salmon ***@***.***>
Sent: Tuesday, October 10, 2023 2:59:08 AM
To: ropensci/censo2017-cartografias ***@***.***>
Cc: Mauricio Andres Vargas Sepulveda ***@***.***>; Mention ***@***.***>
Subject: [ropensci/censo2017-cartografias] What is this repo? (Issue #1)


@pachadotdev<https://github.com/pachadotdev> could we transfer this repository back to your account, as it's not a package?

@ropensci/admin<https://github.com/orgs/ropensci/teams/admin> @jeroen<https://github.com/jeroen>

**Comment by maelle** [comment]
I will first have to transfer it to myself then to you but I see you already have a fork of this repo. You first have to delete the fork, otherwise I won't be able to transfer it to you.

**Comment by pachadotdev** [comment]
> I will first have to transfer it to myself then to you but I see you already have a fork of this repo. You first have to delete the fork, otherwise I won't be able to transfer it to you.

ready

this is jsut the HD version of the census' cartography

**Comment by maelle** [comment]
@pachadotdev transfer requested!

**Comment by pachadotdev** [comment]
@maelle  it says "Oops! That repository transfer request is invalid. Did you copy the URL correctly?"

**Comment by maelle** [comment]
Requested again:

![image](https://github.com/maelle/censo2017-cartografias/assets/8360597/2bb73883-ca6e-4b49-be08-cb0ff30f5150)

**Comment by pachadotdev** [comment]
> Requested again:
> 
> ![image](https://user-images.githubusercontent.com/8360597/275142237-2bb73883-ca6e-4b49-be08-cb0ff30f5150.png)

it says "Oops! That repository transfer has expired."

**Comment by maelle** [comment]
Transfer requested again, it hadn't expired though (I guess you clicked on the link from the first attempted transfer). Hopefully third time's a charm. :sweat_smile:

**Comment by maelle** [comment]
@pachadotdev please accept the transfer

**Comment by pachadotdev** [comment]
@maelle can we please try again? yesterday it also said "link expired"

**Comment by maelle** [comment]
No, the transfer hasn't expired, since to generate one I would need to abort the current one. Are you sure you're looking at the most recent notification/email.

If there's no important metadata in the repository (issues, PRs) I'd suggest that we simply delete this one and you recreate one from a local copy.

**Comment by pachadotdev** [comment]
perfect, I have created a support ticket, because I have some releases in the repository that I do not want to lose

**Comment by pachadotdev** [comment]
@maelle Github transferred this on their side. Thanks a lot.

**Comment by maelle** [comment]
:tada: awesome!
